/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.app;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author egorm
 */
public class SidePanelForm extends javax.swing.JPanel {

    /**
     * Creates new form SidePanel
     */
    
    public SidePanelForm(ActionListener pageSwitcher) {
        initComponents();

        SettingsButton.addActionListener(pageSwitcher);
        SettingsButton.setActionCommand("Settings");

        MainButton.addActionListener(pageSwitcher);
        MainButton.setActionCommand("Main");
        
        HomeButton.addActionListener(pageSwitcher);
        HomeButton.setActionCommand("Home");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side_panel = new javax.swing.JPanel();
        SettingsButton = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();
        MainButton = new javax.swing.JButton();
        SculptureLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(43, 51, 61));

        side_panel.setBackground(new java.awt.Color(43, 51, 61));
        side_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SettingsButton.setBackground(new java.awt.Color(43, 51, 61));
        SettingsButton.setForeground(new java.awt.Color(221, 221, 221));
        SettingsButton.setText("S e t t i n g s");
        SettingsButton.setBorder(null);
        side_panel.add(SettingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 120, 40));

        HomeButton.setBackground(new java.awt.Color(43, 51, 61));
        HomeButton.setForeground(new java.awt.Color(221, 221, 221));
        HomeButton.setText("H o m e");
        HomeButton.setToolTipText("");
        HomeButton.setBorder(null);
        side_panel.add(HomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, 40));

        MainButton.setBackground(new java.awt.Color(43, 51, 61));
        MainButton.setForeground(new java.awt.Color(221, 221, 221));
        MainButton.setText("M a i n");
        MainButton.setBorder(null);
        side_panel.add(MainButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 120, 40));

        SculptureLabel.setIcon(new javax.swing.ImageIcon("D:\\JavaMainTask\\App\\src\\main\\resources\\images\\sculpture.png")); // NOI18N
        side_panel.add(SculptureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 120, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(side_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(side_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton MainButton;
    private javax.swing.JLabel SculptureLabel;
    private javax.swing.JButton SettingsButton;
    private javax.swing.JPanel side_panel;
    // End of variables declaration//GEN-END:variables
}
