/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import main.app.FileSettings;
import main.app.SettingsManager;

/**
 *
 * @author egorm
 */
public class SettingsPageForm extends javax.swing.JPanel {

    /**
     * Creates new form SettingsPageForm
     */
    public SettingsPageForm() {
        initComponents();
        SaveButton.addActionListener(e -> {
            FileSettings fileSettings = new FileSettings.Builder()
                    .setInputFileName(InputFileTextField.getText())
                    .setInputDirectoryPath(InputPatchTextField.getText())
                    .setInputFileArchive(InputArchiveTextField.getText())
                    .setInputFileKey(InputKeyTextField.getText())
                    .setOutputFileName(OutputFileTextField.getText())
                    .setOutputFileType((String) OutputExtencionComboBox.getSelectedItem())
                    .setOutputDirectoryPath(OutputPatchTextField.getText())
                    .setOutputFileArchive(OutputArchiveTextField.getText())
                    .setOutputFileKey(OutputKeyTextField.getText())
                    .build();

            SettingsManager.getInstance().setFileSettings(fileSettings);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outputPanel = new javax.swing.JPanel();
        outputLabel = new javax.swing.JLabel();
        OutputWhitePanel = new javax.swing.JPanel();
        outputFileLabel = new javax.swing.JLabel();
        OutputArchiveLabel = new javax.swing.JLabel();
        OutputPatchLabel = new javax.swing.JLabel();
        outputKeyLabel = new javax.swing.JLabel();
        OutputFileTextField = new javax.swing.JTextField();
        OutputArchiveTextField = new javax.swing.JTextField();
        OutputPatchTextField = new javax.swing.JTextField();
        OutputKeyTextField = new javax.swing.JTextField();
        ChooseOutputFileButton = new javax.swing.JButton();
        OutputExtencionLabel = new javax.swing.JLabel();
        OutputExtencionComboBox = new javax.swing.JComboBox<>();
        OutputIconLabel = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        inputLabel = new javax.swing.JLabel();
        InputWhitePanel = new javax.swing.JPanel();
        InputFileLabel = new javax.swing.JLabel();
        InputArchiveLabel = new javax.swing.JLabel();
        InputPatchLabel = new javax.swing.JLabel();
        InputKeyLabel = new javax.swing.JLabel();
        InputFileTextField = new javax.swing.JTextField();
        InputArchiveTextField = new javax.swing.JTextField();
        InputPatchTextField = new javax.swing.JTextField();
        InputKeyTextField = new javax.swing.JTextField();
        ChooseInputFileButton = new javax.swing.JButton();
        InputIconLabel = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(35, 40, 44));

        outputPanel.setBackground(new java.awt.Color(44, 51, 57));

        outputLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        outputLabel.setForeground(new java.awt.Color(221, 221, 220));
        outputLabel.setText("O U T P U T");

        OutputWhitePanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout OutputWhitePanelLayout = new javax.swing.GroupLayout(OutputWhitePanel);
        OutputWhitePanel.setLayout(OutputWhitePanelLayout);
        OutputWhitePanelLayout.setHorizontalGroup(
            OutputWhitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        OutputWhitePanelLayout.setVerticalGroup(
            OutputWhitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        outputFileLabel.setForeground(new java.awt.Color(221, 221, 220));
        outputFileLabel.setText("F i l e :");

        OutputArchiveLabel.setForeground(new java.awt.Color(221, 221, 220));
        OutputArchiveLabel.setText("A r c h i v e :");

        OutputPatchLabel.setForeground(new java.awt.Color(221, 221, 220));
        OutputPatchLabel.setText("P a t c h :");

        outputKeyLabel.setForeground(new java.awt.Color(221, 221, 220));
        outputKeyLabel.setText("K e y :");

        OutputFileTextField.setBackground(new java.awt.Color(40, 40, 39));
        OutputFileTextField.setForeground(new java.awt.Color(221, 221, 220));

        OutputArchiveTextField.setBackground(new java.awt.Color(40, 40, 39));
        OutputArchiveTextField.setForeground(new java.awt.Color(221, 221, 220));

        OutputPatchTextField.setBackground(new java.awt.Color(40, 40, 39));
        OutputPatchTextField.setForeground(new java.awt.Color(221, 221, 220));

        OutputKeyTextField.setBackground(new java.awt.Color(40, 40, 39));
        OutputKeyTextField.setForeground(new java.awt.Color(221, 221, 220));

        ChooseOutputFileButton.setBackground(new java.awt.Color(86, 86, 87));
        ChooseOutputFileButton.setForeground(new java.awt.Color(221, 221, 220));
        ChooseOutputFileButton.setText("...");

        OutputExtencionLabel.setForeground(new java.awt.Color(221, 221, 220));
        OutputExtencionLabel.setText("E x t e n s i o n :");

        OutputExtencionComboBox.setBackground(new java.awt.Color(86, 86, 87));
        OutputExtencionComboBox.setForeground(new java.awt.Color(221, 221, 220));
        OutputExtencionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "txt", "yaml", "xml", "json", "html" }));
        OutputExtencionComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        OutputIconLabel.setIcon(new javax.swing.ImageIcon("D:\\JavaMainTask\\App\\src\\main\\resources\\images\\output_img.png")); // NOI18N

        javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
        outputPanel.setLayout(outputPanelLayout);
        outputPanelLayout.setHorizontalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(outputPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(OutputExtencionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(outputKeyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OutputPatchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OutputArchiveLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(outputFileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(OutputIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(outputPanelLayout.createSequentialGroup()
                        .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OutputWhitePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(outputPanelLayout.createSequentialGroup()
                                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(OutputExtencionComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 235, Short.MAX_VALUE)
                                    .addComponent(OutputKeyTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(OutputPatchTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(OutputArchiveTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(OutputFileTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ChooseOutputFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        outputPanelLayout.setVerticalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(outputPanelLayout.createSequentialGroup()
                        .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OutputWhitePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(OutputIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OutputFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChooseOutputFileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OutputArchiveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OutputArchiveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OutputPatchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OutputPatchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputKeyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OutputKeyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OutputExtencionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OutputExtencionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        outputLabel.getAccessibleContext().setAccessibleName("");

        inputPanel.setBackground(new java.awt.Color(44, 51, 57));

        inputLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        inputLabel.setForeground(new java.awt.Color(221, 221, 220));
        inputLabel.setText("I N P U T");

        InputWhitePanel.setBackground(new java.awt.Color(255, 255, 255));
        InputWhitePanel.setPreferredSize(new java.awt.Dimension(250, 3));

        javax.swing.GroupLayout InputWhitePanelLayout = new javax.swing.GroupLayout(InputWhitePanel);
        InputWhitePanel.setLayout(InputWhitePanelLayout);
        InputWhitePanelLayout.setHorizontalGroup(
            InputWhitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        InputWhitePanelLayout.setVerticalGroup(
            InputWhitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        InputFileLabel.setForeground(new java.awt.Color(221, 221, 220));
        InputFileLabel.setText("F i l e :");

        InputArchiveLabel.setForeground(new java.awt.Color(221, 221, 220));
        InputArchiveLabel.setText("A r c h i v e :");

        InputPatchLabel.setForeground(new java.awt.Color(221, 221, 220));
        InputPatchLabel.setText("P a t c h :");

        InputKeyLabel.setForeground(new java.awt.Color(221, 221, 220));
        InputKeyLabel.setText("K e y :");

        InputFileTextField.setBackground(new java.awt.Color(40, 40, 39));
        InputFileTextField.setForeground(new java.awt.Color(221, 221, 220));

        InputArchiveTextField.setBackground(new java.awt.Color(40, 40, 39));
        InputArchiveTextField.setForeground(new java.awt.Color(221, 221, 220));

        InputPatchTextField.setBackground(new java.awt.Color(40, 40, 39));
        InputPatchTextField.setForeground(new java.awt.Color(221, 221, 220));

        InputKeyTextField.setBackground(new java.awt.Color(40, 40, 39));
        InputKeyTextField.setForeground(new java.awt.Color(221, 221, 220));
        InputKeyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputKeyTextFieldActionPerformed(evt);
            }
        });

        ChooseInputFileButton.setBackground(new java.awt.Color(86, 86, 87));
        ChooseInputFileButton.setForeground(new java.awt.Color(221, 221, 220));
        ChooseInputFileButton.setText("...");

        InputIconLabel.setIcon(new javax.swing.ImageIcon("D:\\JavaMainTask\\App\\src\\main\\resources\\images\\input_img.png")); // NOI18N

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(InputKeyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InputPatchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InputArchiveLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                        .addComponent(InputFileLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(InputIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputWhitePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(InputKeyTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(InputPatchTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InputArchiveTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InputFileTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ChooseInputFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InputIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputWhitePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InputFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ChooseInputFileButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputArchiveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputArchiveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputPatchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputPatchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputKeyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputKeyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputLabel.getAccessibleContext().setAccessibleName("");

        SaveButton.setBackground(new java.awt.Color(86, 86, 85));
        SaveButton.setForeground(new java.awt.Color(221, 221, 220));
        SaveButton.setText("S a v e ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(outputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(368, Short.MAX_VALUE)
                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(359, 359, 359))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(outputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void InputKeyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputKeyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputKeyTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChooseInputFileButton;
    private javax.swing.JButton ChooseOutputFileButton;
    private javax.swing.JLabel InputArchiveLabel;
    private javax.swing.JTextField InputArchiveTextField;
    private javax.swing.JLabel InputFileLabel;
    private javax.swing.JTextField InputFileTextField;
    private javax.swing.JLabel InputIconLabel;
    private javax.swing.JLabel InputKeyLabel;
    private javax.swing.JTextField InputKeyTextField;
    private javax.swing.JLabel InputPatchLabel;
    private javax.swing.JTextField InputPatchTextField;
    private javax.swing.JPanel InputWhitePanel;
    private javax.swing.JLabel OutputArchiveLabel;
    private javax.swing.JTextField OutputArchiveTextField;
    private javax.swing.JComboBox<String> OutputExtencionComboBox;
    private javax.swing.JLabel OutputExtencionLabel;
    private javax.swing.JTextField OutputFileTextField;
    private javax.swing.JLabel OutputIconLabel;
    private javax.swing.JTextField OutputKeyTextField;
    private javax.swing.JLabel OutputPatchLabel;
    private javax.swing.JTextField OutputPatchTextField;
    private javax.swing.JPanel OutputWhitePanel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel outputFileLabel;
    private javax.swing.JLabel outputKeyLabel;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JPanel outputPanel;
    // End of variables declaration//GEN-END:variables
}
