/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import ui.actions.ActionController;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import settings.FileSettings;
import settings.SettingsManager;

/**
 *
 * @author egorm
 */
public class MainPageForm extends javax.swing.JPanel implements PropertyChangeListener {

    /**
     * Creates new form MainPageForm
     */
    public MainPageForm() {
        SettingsManager.getInstance().addObserver(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputScrollPane = new javax.swing.JScrollPane();
        inputTextArea = new javax.swing.JTextArea();
        outputScrollPane = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();
        readButton = new javax.swing.JButton();
        calculate_Button = new javax.swing.JButton();
        writeButton = new javax.swing.JButton();
        inputLabel = new javax.swing.JLabel();
        outputLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(35, 40, 44));

        inputTextArea.setBackground(new java.awt.Color(40, 40, 41));
        inputTextArea.setColumns(20);
        inputTextArea.setForeground(new java.awt.Color(221, 221, 220));
        inputTextArea.setRows(5);
        inputScrollPane.setViewportView(inputTextArea);

        outputTextArea.setBackground(new java.awt.Color(40, 40, 41));
        outputTextArea.setColumns(20);
        outputTextArea.setForeground(new java.awt.Color(221, 221, 220));
        outputTextArea.setRows(5);
        outputScrollPane.setViewportView(outputTextArea);

        readButton.setBackground(new java.awt.Color(86, 86, 87));
        readButton.setForeground(new java.awt.Color(221, 221, 220));
        readButton.setText("R e a d");
        readButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        readButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readButtonActionPerformed(evt);
            }
        });

        calculate_Button.setBackground(new java.awt.Color(86, 86, 87));
        calculate_Button.setForeground(new java.awt.Color(221, 221, 220));
        calculate_Button.setText("C a l c u l a t e");
        calculate_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calculate_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate_ButtonActionPerformed(evt);
            }
        });

        writeButton.setBackground(new java.awt.Color(86, 86, 87));
        writeButton.setForeground(new java.awt.Color(221, 221, 220));
        writeButton.setText("W r i t e");
        writeButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        writeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeButtonActionPerformed(evt);
            }
        });

        inputLabel.setBackground(new java.awt.Color(30, 30, 31));
        inputLabel.setForeground(new java.awt.Color(221, 221, 220));
        inputLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputLabel.setText("I N P U T ");

        outputLabel.setBackground(new java.awt.Color(30, 30, 31));
        outputLabel.setForeground(new java.awt.Color(221, 221, 220));
        outputLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outputLabel.setText("O U T P U T");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(inputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(outputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(outputScrollPane)
            .addComponent(inputScrollPane)
            .addGroup(layout.createSequentialGroup()
                .addComponent(readButton, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addGap(142, 142, 142)
                .addComponent(calculate_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addGap(143, 143, 143)
                .addComponent(writeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(calculate_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(writeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(readButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addComponent(outputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void readButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonActionPerformed
        // TODO add your handling code here:
        actionController.onReadButtonClick();
    }//GEN-LAST:event_readButtonActionPerformed

    private void calculate_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate_ButtonActionPerformed
        // TODO add your handling code here:
        actionController.onAnalyzeButtonClick();
    }//GEN-LAST:event_calculate_ButtonActionPerformed

    private void writeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeButtonActionPerformed
        // TODO add your handling code here:
        actionController.onWriteButtonClick();
    }//GEN-LAST:event_writeButtonActionPerformed


    private ActionController actionController; 
    private FileSettings fileSettings;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculate_Button;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JScrollPane inputScrollPane;
    private javax.swing.JTextArea inputTextArea;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JScrollPane outputScrollPane;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JButton readButton;
    private javax.swing.JButton writeButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if ("fileSettings".equals(evt.getPropertyName())) {
            actionController = new ActionController((FileSettings) evt.getNewValue(), inputTextArea, outputTextArea);            
        }
    }
}
